name: Build and Deploy
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      bcrCommitHash:
        description: 'Commit hash of the BCR repository to use as the source for the build'
        type: string
  workflow_call:
    inputs:
      bcrCommitHash:
        description: 'Commit hash of the BCR repository to use as the source for the build'
        type: string
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Checkout BCR submodule
        run: |
          git submodule update --init -- data/bazel-central-registry

      - name: Checkout latest commit of BCR submodule
        if:  ${{ !inputs.bcrCommitHash }}
        working-directory: data/bazel-central-registry
        run: |
          git checkout origin/main

      - name: Checkout specific commit of BCR submodule
        if:  ${{ inputs.bcrCommitHash }}
        working-directory: data/bazel-central-registry
        run: |
          git checkout ${{ inputs.bcrCommitHash }}

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm install --frozen-lockfile
          npm run build
          npm run export

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './out'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}