name: Build and Deploy UI to GitHub Pages

on:
  push:
    branches:
      - Aymen-Soussi-01-update-ui-with-our-bazel-registry-modules
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm prettier --write .

      - name: Build and export project
        run: |
          pnpm run build
          pnpm run export
          touch out/.nojekyll  # prevent GitHub Pages from ignoring _next folder

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          commit_message: "Deploying to gh-pages from @ ${{ github.sha }}"
