name: Build & Deploy UI

on:
  push:
    branches:
      - Aymen-Soussi-01-update-ui-with-our-bazel-registry-modules
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Checkout BCR submodule
        run: |
          git submodule update --init --recursive --remote -- data/bazel-central-registry

      - name: Build the UI
        run: pnpm run build

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          commit_message: "Deploying to gh-pages from @ ${{ github.sha }} 🚀"
